version: "3.9"
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - PORT=3000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: node index.js
    environment:
      - PORT=3001
